### ISSUE TITLE
Mistake in _read_data

### ISSUE THREAD

**Issue by kolcz** [adafruit/Adafruit_CircuitPython_SCD4X#19]
adafruit-circuitpython-scd4x version 1.4.2

In method **_read_data** of class **SCD4x** is mistake in calculating **self._temperature** and ****self._realtive_humidity**. Denominator is missing **"- 1"** according to documentation.
Code snippet from library from pip:
![image](https://github.com/adafruit/Adafruit_CircuitPython_SCD4X/assets/17905157/139d1cc9-502a-4ac6-a317-9e89636d1d23)

Fragment from Data Sheet:
![image](https://github.com/adafruit/Adafruit_CircuitPython_SCD4X/assets/17905157/e9d1e08b-85ba-4572-bb6b-e6eb9c426a98)

**Comment by kolcz** [comment]
#20

**Comment by FoamyGuy** [comment]
resolved by #20
