### ISSUE TITLE
Constructor parameter in docs but not code

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_CircuitPython_SCD4X#3]
![Screenshot from 2021-07-27 09-39-48](https://user-images.githubusercontent.com/70200140/127124065-75cdc210-c116-4de1-9287-ca893cb4121b.png)
The `ambient_pressure` constructor parameter is listed in the docs but it is not implemented in the code.

Should this be removed from the docs or added to the code?
I can submit a PR for either preference.

**Comment by ladyada** [comment]
woops yeah please remove that line from the dox - it was a copy paste error (we have a different funciton to set the ambient pressure)
